version: '3.3'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: jenkins.Dockerfile
    privileged: true
    user: root
    environment:
    # change this for default admin login and password
    - JENKINS_USER=admin
    - JENKINS_PASS=admin
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./work/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jobs/docker-builder:/var/jenkins_home/jobs/docker-builder
  registry:
    image: registry:2.7.1
    user: root
    container_name: registry
    ports:
    - 5000:5000
    privileged: true
    volumes:
    - ./work/registry:/var/lib/registry
